// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpMore: typeof import('~icons/ep/more')['default']
    IEpMoreFilled: typeof import('~icons/ep/more-filled')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
  }
}

export {}
